"Resource/UI/StatPanel_PlayTime.res"
{
	"StatPanelBG"
	{
		"ControlName"		"CTFImagePanel"
		"fieldName"		"StatPanelBG"
		"xpos"			"9999"
		"ypos"			"9999"
		"zpos"			"0"
		"wide"			"0"
		"wide_lodef"	"0"
		"tall"			"0"
		"tall_lodef"	"0"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/death_panel_blue_bg"
		"scaleImage"		"1"	
		"teambg_2"		"../hud/death_panel_red_bg"
		"teambg_3"		"../hud/death_panel_blue_bg"
	}
	"StatPanelClassImage"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"StatPanelClassImage"
		"xpos"			"9999"
		"xpos_lodef"	"9999"
		"ypos"			"9999"
		"ypos_lodef"	"9999"
		"zpos"			"1"
		"wide"			"0"
		"wide_lodef"	"0"
		"tall"			"0"
		"tall_lodef"	"0"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/class_scoutred"
		"scaleImage"		"1"	
	}
	"titleLable"
	{	
		"ControlName"	"Label"
		"fieldName"		"titleLable"
		"font"			"TFFontSmall"
		"font_lodef"	"HudFontSmall"
		"xpos"			"9999"
		"xpos_lodef"	"9999"
		"ypos"			"9999"
		"ypos_lodef"	"9999"
		"zpos"			"2"
		"wide"			"0"
		"wide_lodef"	"0"
		"tall"			"0"
		"tall_lodef"	"0"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"labelText"		"%title%"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
	}
	"summaryLabel"
	{	
		"ControlName"	"Label"
		"fieldName"		"summaryLabel"
		"font"			"TFFontMedium"
		"font_lodef"		"HudFontSmall"
		"xpos"			"9999"
		"xpos_lodef"	"9999"
		"ypos"			"9999"
		"ypos_lodef"	"9999"
		"zpos"			"2"
		"wide"			"0"
		"wide_lodef"	"0"
		"tall"			"0"
		"tall_lodef"	"0"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"labelText"		"%statdesc%"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"			"1"
	}
	"StatLabelLarge"
	{	
		"ControlName"		"Label"
		"fieldName"		"StatLabelLarge"
		"font"			"HudFontMedium"
		"xpos"			"9999"
		"xpos_lodef"	"9999"
		"ypos"			"9999"
		"ypos_hidef"	"9999"
		"ypos_lodef"	"9999"
		"zpos"			"3"
		"wide"			"0"
		"tall"			"0"
		"tall_lodef"	"0"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"labelText"		"%stattextlarge%"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
	}
	"StatLabelSmall"
	{	
		"ControlName"		"Label"
		"fieldName"		"StatLabelSmall"
		"font"			"TFFontMedium"
		"font_lodef"		"HudFontSmall"
		"xpos"			"9999"
		"xpos_lodef"	"9999"
		"ypos"			"9999"
		"ypos_lodef"	"9999"
		"zpos"			"3"
		"wide"			"0"
		"tall"			"0"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"labelText"		"%stattextsmall%"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
	}
	StatBox
	{
		"ControlName"		"Panel"		
		"fieldName"		"StatBox"
		"visible"		"1"
		"enabled"		"1"
		"pinCorner"		"0"
		"xpos"			"9999"
		"xpos_lodef"	"9999"
		"ypos"			"9999"
		"ypos_lodef"	"9999"
		"zpos"			"3"
		"wide"			"0"
		"wide_lodef"	"0"
		"tall"			"0"
		"tall_lodef"	"0"
		"PaintBackgroundType"	"2"
	}
}
